config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'widgets#index'
  resources :widgets, only: [:index, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/widget.rb
class Widget < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
    def show
        render "widgets/#{params[:widget]}"
    end

    def new
        @widget = Widget.new
    end
    
    def index
        @widgets = Widget.all
        @widget = Widget.new
    end

    def create
        @widget = Widget.new(params.require(:widget).permit(:description, :quantity))
        @widget.save
        redirect_to root_path
    end

    def destroy
        @widget = Widget.find(params[:id])
        @widget.destroy
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WackyWigets</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/widgets/index.html.erb
<div id= "wrapper">
    <div class= "well">
        <h1>Wacky Widgets</h1>
    </div>
        <% if @widgets.count == 0 %>
        <h3 class="text-center">No Widgets Exist</h3>
        <% else %>
    <table>
        <tr>
        <th>Description</th><th>Quantity</th><th>Remove</th>
        </tr>
        <% total = 0 %>
        <% @widgets.each do |w| %>
        <% total += w.quantity %>
        <tr>
            <td><%= w.description %></td>
            <td><%= w.quantity %></td>
            <td><%= link_to "X", widget_path(w), method: :delete, class: 'btn btn-xs btn-danger' %></td>
        </tr>
        <% end %>
        <tr>
        <td>Total Quantity</td>
        <td><%= total %></td>
        <td></td>
        </tr>
    </table>
    <% end %>
    <hr>
    <h4>Add Widget:</h4>
    <%= form_for @widget do |f| %>
        <div class="form-group">
            <%= f.label :description %>
            <%= f.text_field :description, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :quantity %>
            <%= f.text_field :quantity, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.submit "Add Widget", class: "btn btn-success" %>
        </div>
    <% end %>
</div>